### ISSUE TITLE
1.0 images contain strange artifacts in oblique, oblique angled, isometric and FATISO

### ISSUE THREAD

**Issue by Pewmaymen** [udoprog/c10t#226]
When generating images, the latest version from github as of 01/04/2012 creates images that have strange rendering artifacts if any of the "angled view" image types are used (top-down, flat-world is fine).  This doesn't occur in the last stable binary build (git 43336eb from Mar 21, 2011).  

For an example, see:  ftp://download:secret@files.egenera.com/shawn/minecraft_maps/isometric_daily_1.0_keep.png

Shawn

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Pewmaymen)
