### ISSUE TITLE
Unable to generate a full map if there are more that ~1000 chunks in any direction

### ISSUE THREAD

**Issue by Pewmaymen** [udoprog/c10t#227]
I have a map that has the following chunk limits: 
  min_x: -174
  max_x: 1542 (I put this here by hand)
  min_z: -216
  max_z: 316
  levels: 127275

 If I try and generate a map of this world (1Gig in disk space size), c10t will stop at a max_x of 986 even with a -L -216,316,-174,1542 specified.  
Here is debug output up to the Rendering stage:
c10t -w /tickets/shawn/minecraft/survival/survival -o /downloads/shawn/minecraft_maps/isometric_hourly_surv_survival.png -y -r 270 -m 16 -M 8192 --debug -L -216,316,-174,1542 | more

Generating PNG Map

 --- SCANNING WORLD DIRECTORY --- 
world: /tickets/shawn/minecraft/survival/survival
...............................     3100 parts
...............................     6200 parts
...............................     9300 parts
...............................    12400 parts
...............................    15500 parts
...............................    18600 parts
...............................    21700 parts
...............................    24800 parts
...............................    27900 parts
...............................    31000 parts
...............................    34100 parts
...............................    37200 parts
...............................    40300 parts
...............................    43400 parts
...............................    46500 parts
...............................    49600 parts
...............................    52700 parts
...............................    55800 parts
...............................    58900 parts
...............................    62000 parts
...............................    65100 parts
...............................    68200 parts
...............................    71300 parts
...............................    74400 parts
...............................    77500 parts
...............................    80600 parts
...............................    83700 parts
...............................    86800 parts
...............................    89900 parts
...............................    93000 parts
...............................    96100 parts
...............................    99200 parts
...............................   102300 parts
...............................   105400 parts
...............................   108500 parts
...............................   111600 parts
...............................   114700 parts
.........................   117255 parts
SEE LOG: 77852 level(s) filtered!
 --- DEBUG WORLD INFO --- 
mc::world
  min_x: -174
  max_x: 986
  min_z: -216
  max_z: 216
  levels: 117255
  chunk pos: 0x0
 --- ALLOCATING MEMORY --- 
memory usage: 2493 MB
memory limit: 8192 MB
 --- RENDERING --- 

This is using c10t from git as of 9PM Eastern time on Jan 4, 2012.  

This world can be grabbed for test at:
ftp://download:supersecret@files.egenera.com/shawn/minecraft_maps/survival.7z

It is compressed/archived with 7z and is 620M compressed and 1Gig uncompressed.  

Shawn

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Pewmaymen)
