### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by Sworddragon** [udoprog/c10t#270]
I'm using the latest version of c10t with the GCC 4.7.1 and I'm getting a few compiler warnings:

> [ 66%] Building CXX object CMakeFiles/c10t.dir/src/main.cpp.o
> In file included from /home/sworddragon/.git/c10t/src/main.cpp:18:0:
> /home/sworddragon/.git/c10t/src/json.hpp: In destructor ‘json::object::~object()’:
> /home/sworddragon/.git/c10t/src/json.hpp:120:24: warning: deleting object of abstract class type ‘json::basic_json’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
> /home/sworddragon/.git/c10t/src/json.hpp: In destructor ‘json::array::~array()’:
> /home/sworddragon/.git/c10t/src/json.hpp:158:19: warning: deleting object of abstract class type ‘json::basic_json’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
> [ 88%] Building CXX object CMakeFiles/c10t.dir/src/json.cpp.o
> In file included from /home/sworddragon/.git/c10t/src/json.cpp:1:0:
> /home/sworddragon/.git/c10t/src/json.hpp: In destructor ‘json::object::~object()’:
> /home/sworddragon/.git/c10t/src/json.hpp:120:24: warning: deleting object of abstract class type ‘json::basic_json’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
> /home/sworddragon/.git/c10t/src/json.hpp: In destructor ‘json::array::~array()’:
> /home/sworddragon/.git/c10t/src/json.hpp:158:19: warning: deleting object of abstract class type ‘json::basic_json’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
> [ 91%] Building CXX object CMakeFiles/c10t.dir/src/generate_map.cpp.o
> In file included from /home/sworddragon/.git/c10t/src/generate_map.cpp:31:0:
> /home/sworddragon/.git/c10t/src/json.hpp: In destructor ‘json::object::~object()’:
> /home/sworddragon/.git/c10t/src/json.hpp:120:24: warning: deleting object of abstract class type ‘json::basic_json’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
> /home/sworddragon/.git/c10t/src/json.hpp: In destructor ‘json::array::~array()’:
> /home/sworddragon/.git/c10t/src/json.hpp:158:19: warning: deleting object of abstract class type ‘json::basic_json’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]

**Comment by tanaka141** [comment]
I juste made the modification proposed by Evildeeds https://github.com/evildeeds/c10t/commit/bd365e4ac2870783bbe65c99b94a4f13a28946f9 and errors with ‘json::object::~object()’ disappear.
