### ISSUE TITLE
Build failure with Boost 1.85.0

### ISSUE THREAD

**Issue by cho-m** [udoprog/c10t#313]
Building with Boost 1.85.0 results in errors due to usage of removed APIs, e.g.
```
/tmp/c10t-20240425-93145-ldcb56/c10t-1.7/src/mc/utils.cpp:86:30: error: no member named 'extension' in namespace 'boost::filesystem'
      string extension = fs::extension(path);
                         ~~~~^
/tmp/c10t-20240425-93145-ldcb56/c10t-1.7/src/mc/utils.cpp:89:24: error: no member named 'basename' in namespace 'boost::filesystem'
      split(parts, fs::basename(path), '.');
                   ~~~~^
/tmp/c10t-20240425-93145-ldcb56/c10t-1.7/src/mc/utils.cpp:107:30: error: no member named 'extension' in namespace 'boost::filesystem'
      string extension = fs::extension(path);
                         ~~~~^
/tmp/c10t-20240425-93145-ldcb56/c10t-1.7/src/mc/utils.cpp:110:24: error: no member named 'basename' in namespace 'boost::filesystem'
      split(parts, fs::basename(path), '.');
                   ~~~~^
```

https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html shows the replacements, i.e.
* Replace `extension(p)` with `p.extension().string()`
* Replace `basename(p)` with `p.stem().string()`

Oldest Boost this project supports looks like 1.46, which should work with above - https://www.boost.org/doc/libs/1_46_0/boost/filesystem/v3/convenience.hpp

**Comment by evildeeds** [comment]
Noted; I only have boost 1.82 installed currently, if you already have patch it would be appreciated, otherwise I will look into this as soon as I have time
